[package]
name = "test_canister"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.9.0"
ic-cdk = "0.10.0"
ic-cdk-timers = "0.5.0"
serde = { version = "1.0", features = ["derive"] } 