[package]
name = "generate-did"
version = "0.1.0"
edition = "2021"
description = "A tool to generate Candid (.did) files for Internet Computer Rust canisters"
license = "MIT"

[dependencies]
thiserror = "1.0"
anyhow = "1.0"
